# Generated by Django 5.2 on 2025-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_video_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='imgages/'),
        ),
    ]
