# Generated by Django 5.2 on 2025-06-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_video_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
