# Generated by Django 5.2 on 2025-06-03 19:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_video_video_file_url_delete_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_upload',
            field=models.FileField(default='videos/defatlt.mp4', storage=django.core.files.storage.FileSystemStorage(location='media/videos'), upload_to='videos/'),
            preserve_default=False,
        ),
    ]
