# Generated by Django 5.2 on 2025-06-03 19:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_video_video_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_upload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/videos'), upload_to=''),
        ),
    ]
