# Generated by Django 5.2 on 2025-06-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_video_video_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_upload',
            field=models.FileField(upload_to='videos'),
        ),
    ]
