# Generated by Django 5.2.4 on 2025-09-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_video_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='imgages/'),
        ),
    ]
