# Generated by Django 5.2.4 on 2025-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_trailer_description_trailer_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
